version: "3.7"

services:
  frontend:
    image: $IMAGE:$TAG
    build: .
    env_file:
      - .env
    networks:
      - default
    restart: unless-stopped



networks:
  default:
    name: $CI_PROJECT_ROOT_NAMESPACE
    external: true